# Generated by Django 4.0 on 2021-12-27 12:48

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=src.base.services.get_path_upload_cover_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), src.base.services.validate_size_image]),
        ),
        migrations.AddField(
            model_name='track',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
