# Generated by Django 4.0 on 2021-12-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('video_library', '0003_video_remove_track_album_remove_track_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(related_name='video_genres', to='video_library.Genre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_videos', to='video_library.license'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='oauth.authuser'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user_of_likes',
            field=models.ManyToManyField(related_name='likes_of_videos', to='oauth.AuthUser'),
        ),
    ]
