# Generated by Django 4.0 on 2021-12-29 12:38

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0004_alter_video_genre_alter_video_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=src.base.services.get_path_upload_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'wav'])]),
        ),
    ]
